export const coinMap: Record<string, string> = {
  bitcoin: 'bitcoin',
  ethereum: 'ethereum',
  xrp: 'ripple',
  solana: 'solana',
  binance: 'binancecoin',
  'binance coin': 'binancecoin',
  'doge coin': 'dogecoin',
  cardano: 'cardano',
  tron: 'tron',
  sui: 'sui',
  chainlink: 'chainlink',
  avalanche: 'avalanche-2',
  'shiba inu': 'shiba-inu',
  stellar: 'stellar',
  polkadot: 'polkadot',
  'bitcoin cash': 'bitcoin-cash',
  bitcoincash: 'bitcoin-cash',
  ton: 'the-open-network',
  pepe: 'pepe',
  hedera: 'hedera-hashgraph',
  polygon: 'matic-network',
  'internet computer': 'internet-computer',
  sonic: 'sonic-2',
  eos: 'eos',
  pancakeswap: 'pancakeswap-token',
  'baby doge coin': 'baby-doge-coin',
};
